### ISSUE TITLE
java.lang.IllegalArgumentException: log10p: Log10-probability must be 0 or less

### ISSUE THREAD

**Issue by xingziye** [gatk-workflows/gatk4-somatic-snvs-indels#25]
Hi,

I had similar issue with what this post had: https://gatkforums.broadinstitute.org/gatk/discussion/23685/issues-on-filtermutectcalls-log10-probability-must-be-0-or-less
```
java.lang.IllegalArgumentException: log10p: Log10-probability must be 0 or less
	at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:724)
	at org.broadinstitute.hellbender.utils.MathUtils.log10BinomialProbability(MathUtils.java:917)
	at org.broadinstitute.hellbender.utils.MathUtils.binomialProbability(MathUtils.java:910)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.ContaminationFilter.calculateErrorProbability(ContaminationFilter.java:56)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2VariantFilter.errorProbability(Mutect2VariantFilter.java:15)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.ErrorProbabilities.lambda$new$1(ErrorProbabilities.java:19)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.ErrorProbabilities.<init>(ErrorProbabilities.java:19)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2FilteringEngine.accumulateData(Mutect2FilteringEngine.java:141)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls.nthPassApply(FilterMutectCalls.java:140)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverse$0(MultiplePassVariantWalker.java:40)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverseVariants$1(MultiplePassVariantWalker.java:77)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverseVariants(MultiplePassVariantWalker.java:75)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverse(MultiplePassVariantWalker.java:40)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Using GATK jar /root/gatk.jar defined in environment variable GATK_LOCAL_JAR
```
Same for me that not all of my tests have this issue but only some of them. It says it is a known issue and has been fixed earlier this year. https://software.broadinstitute.org/gatk/documentation/article?id=23718
Just want to know if this workflow still has this issue not fixed or it is something different. 
Thank you!

**Comment by markw3lsh** [comment]
I am seeing this issue in GATK v4.1.3 as well:
```
16:00:07.124 INFO  FilterMutectCalls - ------------------------------------------------------------
16:00:07.125 INFO  FilterMutectCalls - The Genome Analysis Toolkit (GATK) v4.1.3.0
16:00:07.125 INFO  FilterMutectCalls - For support and documentation go to https://software.broadinstitute.org/gatk/
16:00:07.126 INFO  FilterMutectCalls - Executing as welshm3@c-3-11 on Linux v3.10.0-514.2.2.el7.x86_64 amd64
16:00:07.126 INFO  FilterMutectCalls - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_232-b09
16:00:07.126 INFO  FilterMutectCalls - Start Date/Time: January 16, 2020 4:00:04 PM EST
16:00:07.126 INFO  FilterMutectCalls - ------------------------------------------------------------
16:00:07.126 INFO  FilterMutectCalls - ------------------------------------------------------------
16:00:07.127 INFO  FilterMutectCalls - HTSJDK Version: 2.20.1
16:00:07.127 INFO  FilterMutectCalls - Picard Version: 2.20.5
16:00:07.127 INFO  FilterMutectCalls - HTSJDK Defaults.COMPRESSION_LEVEL : 2
16:00:07.127 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:00:07.127 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:00:07.127 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:00:07.127 INFO  FilterMutectCalls - Deflater: IntelDeflater
16:00:07.127 INFO  FilterMutectCalls - Inflater: IntelInflater
16:00:07.127 INFO  FilterMutectCalls - GCS max retries/reopens: 20
16:00:07.127 INFO  FilterMutectCalls - Requester pays: disabled
16:00:07.127 INFO  FilterMutectCalls - Initializing engine
16:00:07.812 INFO  FeatureManager - Using codec VCFCodec to read file file:///scr1/users/welshm3/cromwell-executions/ScatterFilter/44f4bcf3-beb9-494b-a778-ecd9881844f0/call-FilterMutectCalls/shard-36/inputs/-1583679789/SJNBL050709_D3-FFPE239_G1-FFPE231.merged.vcf
16:00:08.112 INFO  FilterMutectCalls - Done initializing engine
16:00:08.467 INFO  IOUtils - Extracting data from archive: file:///scr1/users/welshm3/cromwell-executions/ScatterFilter/44f4bcf3-beb9-494b-a778-ecd9881844f0/call-FilterMutectCalls/shard-36/inputs/8554068/SJNBL050709_D3-FFPE239_G1-FFPE231.learned_orientation.tar.gz
16:00:08.476 INFO  IOUtils - Extracting file: ./SJNBL050709_D3-FFPE239.orientation_priors
16:00:08.552 INFO  ProgressMeter - Starting traversal
16:00:08.552 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
16:00:08.553 INFO  FilterMutectCalls - Starting pass 0 through the variants
16:00:08.616 INFO  FilterMutectCalls - Shutting down engine
[January 16, 2020 4:00:08 PM EST] org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=243335168
java.lang.IllegalArgumentException: log10p: Log10-probability must be 0 or less
	at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:724)
	at org.broadinstitute.hellbender.utils.MathUtils.log10BinomialProbability(MathUtils.java:934)
	at org.broadinstitute.hellbender.utils.MathUtils.binomialProbability(MathUtils.java:927)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.ContaminationFilter.calculateErrorProbability(ContaminationFilter.java:56)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2VariantFilter.errorProbability(Mutect2VariantFilter.java:15)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.ErrorProbabilities.lambda$new$1(ErrorProbabilities.java:19)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.ErrorProbabilities.<init>(ErrorProbabilities.java:19)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2FilteringEngine.accumulateData(Mutect2FilteringEngine.java:141)
	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls.nthPassApply(FilterMutectCalls.java:146)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverse$0(MultiplePassVariantWalker.java:40)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverseVariants$1(MultiplePassVariantWalker.java:77)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverseVariants(MultiplePassVariantWalker.java:75)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverse(MultiplePassVariantWalker.java:40)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291
```
